// src/components/React/NavBar.tsx
import { useState, useEffect } from 'react'
import { navLinks } from '@/lib/site'
import { cn } from '@/utils/utils'
import MobileMenu from './MobileMenu'

export const NavBar = () => {
  const [isOpen, setIsOpen] = useState(false)
  const [pathname, setPathname] = useState('')

  useEffect(() => {
    if (typeof window !== 'undefined') {
      setPathname(window.location.pathname.split('/')[1] || '')
    }
  }, [])

  const toggleMenu = () => {
    setIsOpen(!isOpen)
    document.body.style.overflow = !isOpen ? 'hidden' : ''
  }

  return (
    <div className="mt-8 flex w-full items-center justify-center px-4 pr-6">
      <nav
        className={cn(
          'text-muted-foreground flex w-full max-w-4xl items-center justify-between rounded-full bg-white shadow-none',
          isOpen && 'rounded-b-none border-b-0'
        )}
      >
        <a
          href="/"
          className="font-cursive rounded-full border border-black/90 px-2 py-1 text-2xl text-black/90 transition-all duration-100 ease-in-out hover:scale-105 hover:-rotate-10 hover:shadow-lg"
          onClick={() => setPathname('')}
        >
          CN
        </a>

        <ul
          className="hidden gap-4 rounded-full border px-4 py-2 text-lg md:flex"
          aria-label="Desktop navigation"
        >
          {navLinks.map(({ href, text }) => {
            const isActive = text === pathname
            return (
              <li key={href}>
                <a
                  href={href}
                  className={cn(
                    'group transition-colors duration-200 ease-in-out hover:text-blue-600',
                    isActive ? 'text-blue-600' : 'text-black'
                  )}
                  aria-current={isActive ? 'page' : undefined}
                  onClick={() => setPathname(text)}
                >
                  {text}
                </a>
              </li>
            )
          })}
        </ul>
        <button
          className="hamburger flex justify-center md:hidden"
          onClick={toggleMenu}
          aria-label="Toggle mobile menu"
          aria-expanded={isOpen}
        >
          <div className="relative flex h-6 w-8 flex-col justify-between">
            <span
              className={cn(
                'absolute h-0.5 w-full bg-black transition-all duration-300',
                isOpen ? 'top-1/2 -translate-y-1/2 rotate-45' : 'top-0'
              )}
            ></span>
            <span
              className={cn(
                'absolute top-1/2 h-0.5 w-full -translate-y-1/2 bg-black transition-all duration-300',
                isOpen ? 'opacity-0' : 'opacity-100'
              )}
            ></span>
            <span
              className={cn(
                'absolute h-0.5 w-full bg-black transition-all duration-300',
                isOpen ? 'top-1/2 -translate-y-1/2 -rotate-45' : 'bottom-0'
              )}
            ></span>
          </div>
        </button>
      </nav>
      <MobileMenu isOpen={isOpen} onClose={toggleMenu} />
    </div>
  )
}

// src/components/Svelte/NavBar.svelte
<script lang="ts">
  import { cn } from '@/utils/utils'
  import { navLinks } from '@/lib/site'
  import { onMount } from 'svelte'
  import MobileMenu from './MobileMenu.svelte'

  let isOpen = false
  let pathname = ''

  onMount(() => {
    pathname = window.location.pathname.split('/')[1]

    return () => {
      document.body.style.overflow = ''
    }
  })

  function toggleMenu() {
    isOpen = !isOpen
    document.body.style.overflow = isOpen ? 'hidden' : ''
  }

  function closeMenu() {
    isOpen = false
    document.body.style.overflow = ''
  }
</script>

<div
  class="top-6 left-0 right-0 w-full flex justify-center items-center pl-4 pr-6 mt-8"
>
  <nav
    class={cn(
      'text-muted-foreground flex items-center justify-between rounded-full w-full max-w-4xl bg-white',
      isOpen ? 'rounded-b-none border-b-0 shadow-none' : 'shadow-none'
    )}
    style="transition: background-color 0.3s, box-shadow 0.3s, border-radius 0.3s;"
  >
    <a
      href="/"
      class="font-cursive rounded-full border px-2 py-1 transition-all duration-100 text-2xl text-blue-600 border-blue-600 hover:shadow-lg hover:-rotate-10 ease-in-out hover:scale-105"
    >
      CN
    </a>

    <ul
      class="hidden list-none gap-4 text-lg md:flex border rounded-full px-4 py-2"
      aria-label="Desktop navigation"
    >
      {#each navLinks as { href, text }}
        {@const isActive = text === pathname}
        <li>
          <a
            {href}
            class={cn(
              'group hover:text-blue-600 transition-colors duration-200 ease-in-out',
              isActive ? 'text-blue-600' : 'text-black'
            )}
            aria-current={isActive ? 'page' : undefined}
            on:click={() => pathname = text}
          >
            {text}
          </a>
        </li>
      {/each}
    </ul>
    <button
      class="hamburger flex justify-center md:hidden"
      on:click={toggleMenu}
      aria-label="Toggle mobile menu"
      aria-expanded={isOpen}
    >
      <div class="relative flex flex-col justify-between w-8 h-6">
        <span
          class={cn(
            'h-0.5 w-full bg-black absolute transition-all duration-300',
            isOpen ? 'top-1/2 -translate-y-1/2 rotate-45' : 'top-0'
          )}
        ></span>
        <span
          class={cn(
            'h-0.5 w-full bg-black absolute top-1/2 -translate-y-1/2 transition-all duration-300',
            isOpen ? 'opacity-0' : 'opacity-100'
          )}
        ></span>
        <span
          class={cn(
            'h-0.5 w-full bg-black absolute transition-all duration-300',
            isOpen ? 'top-1/2 -translate-y-1/2 -rotate-45' : 'bottom-0'
          )}
        ></span>
      </div>
    </button>
  </nav>
</div>

<MobileMenu {isOpen} onClose={closeMenu} />
